# Generated by Django 2.1.3 on 2018-11-14 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField(default='', max_length=1000)),
                ('wikipedia', models.URLField(blank=True)),
                ('tripadvisor', models.URLField(blank=True)),
                ('google_map', models.URLField(blank=True)),
                ('web_site', models.URLField(blank=True)),
                ('town', models.CharField(blank=True, default='', max_length=30)),
                ('image', models.ImageField(blank=True, default='no_image.png', upload_to='')),
                ('image_map', models.ImageField(blank=True, default='no_image.png', upload_to='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=25)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+x xxx xxx xx xx'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('order', models.CharField(max_length=200)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('text', models.TextField(default='', max_length=1000)),
                ('wikipedia', models.URLField(blank=True)),
                ('tripadvisor', models.URLField(blank=True)),
                ('google_map', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, default='no_image.png', upload_to='')),
                ('image_map', models.ImageField(blank=True, default='no_image.png', upload_to='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
